#!/usr/bin/env python3
import sys
import os
from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        print("Usage: tweets [username]")
        return

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    username = sys.argv[1]
    tweets = get_user_timeline(username)
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0:
            print(colored(tweet + " " + str(score), "green"))
        elif score < 0:
            print(colored(tweet + " " + str(score), "red"))
        else:
            print(colored(tweet + " " + str(score), "yellow"))

if __name__ == "__main__":
    main()
